#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${sh_SOURCE[0]}" )" &> /dev/null && pwd )"

# show help if no argument is given
if [[ $# -eq 0 ]]; then
    cat <<EOF
Usage: $0 <package_manager_index>

Arguments:
  <package_manager_index>  The package manager to use (e.g., apt, dnf, pacman)

Example:
  $0 apt

Function:
  Lists available software for that package manager
EOF
    exit 1
fi

# input handling
PACKAGE_MANAGER="$1"
MGRS=~/.config/unipkg/managers.csv

# exctract command
CMD=$(cat "$MGRS" | grep -e "^$PACKAGE_MANAGER" | cut -d ',' -f6)
DisplayName=$(cat $MGRS | grep -e "^$PACKAGE_MANAGER" | cut -d ',' -f2)

# inform user and run command
echo -e "[\e[36mACTION\e[0m] Listing available packages for: \e[33m$DisplayName\e[0m"
eval "$CMD"