#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

CONF=$(cat ~/.config/unipkg/unipkg.conf)
MGRS=~/.config/unipkg/managers.csv
clear
while read -r LINE; do
    CMD=$(cat "$MGRS" | grep -e "^$LINE" | cut -d ',' -f3)
    DisplayName=$(cat $MGRS | grep -e "^$LINE" | cut -d ',' -f2)
    echo ""
    echo -e "[\e[36mACTION\e[0m] Versioning for: \e[33m$DisplayName\e[0m"
    echo ""
    eval $CMD
done <<< $CONF