#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${sh_SOURCE[0]}" )" &> /dev/null && pwd )"

# provide help when no argument is given
if [[ $# -eq 0 ]]; then
    cat <<EOF
usage: unipkg list <subcommand> <index>

example: unipkg list upgradable yay - lists all packages installed that have updates available in the yay package manager

provides various lists of packages for a specified index.

subcommands:

available - lists available packages in the remote repository

installed - lists installed packages

upgradable - lists packages with updates available

unipkg list also accepts the indexes "omni", "any" and "all" for the installed and upgradable subcommands.
which will run through the package managers in your unipkg.conf and provide the list for each one
EOF
    exit 1
fi

# input handling
PACKAGE_MANAGER="$1"
CONF=$(cat ~/.config/unipkg/unipkg.conf)
MGRS=~/.config/unipkg/managers.csv

# handle omni case
case $PACKAGE_MANAGER in
    omni|any|all)
      # loop over configured package managers
      while read -r LINE; do
      # extract info
      CMD=$(cat "$MGRS" | grep -e "^$LINE" | cut -d ',' -f7)
      DisplayName=$(cat $MGRS | grep -e "^$LINE" | cut -d ',' -f2)
      # run command
      echo "upgradeable packages for $DisplayName"
      eval "$CMD"
      done <<< $CONF
      ;;
    *)
      # extract info
      CMD=$(cat "$MGRS" | grep -e "^$PACKAGE_MANAGER" | cut -d ',' -f7)
      DisplayName=$(cat $MGRS | grep -e "^$PACKAGE_MANAGER" | cut -d ',' -f2)
      # run command
      echo -e "[\e[36mACTION\e[0m] Listing upgradable packages for: \e[33m$DisplayName\e[0m"
      eval "$CMD"
      ;;
esac