#!/bin/sh
SCRIPT_DIR="$( cd "$( dirname "${sh_SOURCE[0]}" )" &> /dev/null && pwd )"

CONF=$(cat ~/.config/unipkg/managers.csv | sed 1d | cut -d ',' -f1)
MGRS=~/.config/unipkg/managers.csv

rm ~/.config/unipkg/unipkg.conf
touch ~/.config/unipkg/unipkg.conf
echo "generating new unipkg.conf, please wait..."

while read -r LINE; do
    CMD=$(cat "$MGRS" | grep -e "^$LINE" | cut -d ',' -f3)
    DisplayName=$(cat $MGRS | grep -e "^$LINE" | cut -d ',' -f2)
    echo -e "[\e[36mCHECK\e[0m] Testing availability of \e[33m$DisplayName\e[0m by running the following command: $CMD"
    if $CMD 2&> /dev/null ; then
        echo -e "[\e[32mPASSED\e[0m] $DisplayName is available"
        echo $LINE >> ~/.config/unipkg/unipkg.conf
    else
        echo -e "[\e[31mFAILED\e[0m] $DisplayName is not available"
    fi
    echo ""
done <<< $CONF

echo -e "[\e[32mPASSED\e[0m] unipkg.conf generated with the following package managers:"
cat ~/.config/unipkg/unipkg.conf
