#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${sh_SOURCE[0]}" )" &> /dev/null && pwd )"

# show help if no option was provided
if [[ $# -lt 1 ]]; then
    cat <<EOF
usage: unipkg uninstall <index> <package>

example: unipkg uninstall dnf cowsay - uninstalls dnf with cowsay

uninstalls the package with the provided package manager

unipkg uninstall also accepts the indexes "omni", "any" and "all".
which will run through the package managers in your unipkg.conf and attempt to uninstall the requested package with each one
until it succeeds or runs out of package managers to try.

EOF
    exit 1
fi

# input handling
PACKAGE_MANAGER="$1"
shift
PACKAGE_LIST=("$@")
MGRS=~/.config/unipkg/managers.csv
CONF=$(cat ~/.config/unipkg/unipkg.conf)

# inform user
echo "Selected package manager: $PACKAGE_MANAGER"
echo "Package to process: ${PACKAGE_LIST[*]}"


# handle omni case
case $PACKAGE_MANAGER in
    omni|any|all)
      # loop over unipkg.conf items
      while read -r LINE; do
      # extract info
      INSTALL_CMD=$(cat "$MGRS" | grep -e "^$LINE" | cut -d ',' -f9)
      DisplayName=$(cat $MGRS | grep -e "^$LINE" | cut -d ',' -f2)
      FULL_CMD="$INSTALL_CMD $PACKAGE_LIST"
      # inform user
      echo -e "[\e[36mACTION\e[0m] attempting removal using \e[33m$DisplayName\e[0m"
      echo "running the following command: $FULL_CMD"
      # run the remove command and check its output
      if bash -c "$FULL_CMD" ; then
        echo -e "[\e[32mSUCCESS\e[0m] successfully removed package using $DisplayName"
        exit 0
        # if succesful, exit the script
      else
        echo -e "[\e[31mFAIL\e[0m] failed removal using $DisplayName"
        # loop
      fi
      done <<< $CONF
      echo -e "[\e[31mFAIL\e[0m] Package $PACKAGE_LIST was not removed."
      # failed uninstalling the command with the package managers available.
      ;;
    *)
      # extract info
      CMD=$(cat "$MGRS" | grep -e "^$PACKAGE_MANAGER" | cut -d ',' -f9)
      DisplayName=$(cat $MGRS | grep -e "^$PACKAGE_MANAGER" | cut -d ',' -f2)
      FULL_CMD="$CMD $PACKAGE_LIST"
      # inform user
      echo ""
      echo -e "[\e[36mACTION\e[0m] using \e[33m$DisplayName\e[0m to remove $PACKAGE_LIST"
      echo "${PACKAGE_LIST[*]}"
      echo ""
      # run command
      bash -c "$FULL_CMD"
    ;;
esac