#!/bin/sh
SCRIPT_DIR="$( cd "$( dirname "${sh_SOURCE[0]}" )" &> /dev/null && pwd )"
# Universal Linux Package Manager Wrapper (Flavour 1)
# Usage: ./script.sh <package_manager_index>


# --- Dependency Check ---


# --- Input Handling ---
PACKAGE_MANAGER="$1"

# --- Rest of the script will go here ---
# (e.g., TUI logic, package operations, etc.)
MGRS=~/.config/unipkg/managers.csv
CONF=$(cat ~/.config/unipkg/unipkg.conf)

case $PACKAGE_MANAGER in
    omni|any|all)
      while read -r LINE; do
      CMD=$(cat "$MGRS" | grep -e "^$LINE" | cut -d ',' -f11)
      DisplayName=$(cat $MGRS | grep -e "^$LINE" | cut -d ',' -f2)
      eval "$CMD"
      done <<< $CONF
      ;;
    *)
      CMD=$(cat "$MGRS" | grep -e "^$PACKAGE_MANAGER" | cut -d ',' -f11)
      DisplayName=$(cat $MGRS | grep -e "^$PACKAGE_MANAGER" | cut -d ',' -f2)
      echo -e "[\e[36mACTION\e[0m] Listing installed packages for: \e[33m$DisplayName\e[0m"
      eval "$CMD"
      ;;
esac