#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${sh_SOURCE[0]}" )" &> /dev/null && pwd )"

# set variables
CONF=$(cat ~/.config/unipkg/managers.csv | sed 1d | cut -d ',' -f1)
MGRS=~/.config/unipkg/managers.csv

# remove previous unipkg.conf
rm ~/.config/unipkg/unipkg.conf
touch ~/.config/unipkg/unipkg.conf

# inform user
echo "generating new unipkg.conf, please wait..."

# loop over all lines in managers.csv
while read -r LINE; do
    # extract and strip versioning comand
    CMD=$(cat "$MGRS" | grep -e "^$LINE" | cut -d ',' -f3)
    DisplayName=$(cat $MGRS | grep -e "^$LINE" | cut -d ',' -f2)
    STRIPPED_CMD=$(echo "$CMD" | awk '{print $1}')
    echo -e "[\e[36mCHECK\e[0m] Testing availability of \e[33m$DisplayName\e[0m by running the following command: $CMD"
    # run check
    if command -v $STRIPPED_CMD ; then
        echo -e "[\e[32mPASSED\e[0m] $DisplayName is available"
        # add manager to unipkg.conf if available.
        echo $LINE >> ~/.config/unipkg/unipkg.conf
    else
        echo -e "[\e[31mFAILED\e[0m] $DisplayName is not available"
    fi
    echo ""
done <<< $CONF

# inform user of the result
echo -e "[\e[32mPASSED\e[0m] unipkg.conf generated with the following package managers:"
cat ~/.config/unipkg/unipkg.conf
