#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${sh_SOURCE[0]}" )" &> /dev/null && pwd )"

# present help if no arguments are provided
if [[ $# -lt 1 ]]; then
    cat <<EOF
Usage: $0 <index> <package>

Arguments:
  <index>  The package manager to use (e.g., apt, dnf, pacman)
  <package>  package to get information about

Example:
  $0 apt curl

Function:
  gets information about a package

EOF
    exit 1
fi

# input handling
PACKAGE_MANAGER="$1"
shift 
PACKAGE_LIST=("$@")
MGRS=~/.config/unipkg/managers.csv

# core function
CMD=$(cat "$MGRS" | grep -e "^$PACKAGE_MANAGER" | cut -d ',' -f4)
DisplayName=$(cat $MGRS | grep -e "^$PACKAGE_MANAGER" | cut -d ',' -f2)
echo ""
echo -e "[\e[36mACTION\e[0m] listing \e[33m$DisplayName\e[0m information for: $PACKAGE_LIST"
echo ""
eval "$CMD $PACKAGE_LIST"